### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by SaitamaSiSi** [idrawjs/idraw#131]
![image](https://user-images.githubusercontent.com/70926594/150279124-1eea5ae4-a92c-427c-bfb6-15d3d7c87f5c.png)
你好，我有两个问题想请教一下，在VS2019+Vue中引用idraw生成画布后，鼠标在画布中移动等就会一直不断弹出这个异常，请问是什么问题呢，顺带想问一下双击编辑文本框内容是怎么实现的呢

**Comment by chenshenhai** [comment]
@SaitamaSiSi 您好！
- 请问出现报错是在什么浏览器环境？
- 关于双击文本显示编辑框，是计算文本尺寸，动态生成一个 `textarea` 标签显示处理编辑的。

**Comment by SaitamaSiSi** [comment]
@chenshenhai 
谢谢您的回复，我是在谷歌浏览器97.0.4692.71(正式版本)(64位)中出现的。
使用的JavaScript，Vs2019+@vue/cli 4.5.13，vue版本2.6.12，node.js版本v14.16.1，idraw版本0.2.0-alpha.25。
该问题在Microsoft Edge 97.0.1072.62 (官方内部版本) (64 位)中也会出现。

**Comment by chenshenhai** [comment]
@SaitamaSiSi 我还原了Windows环境里环境里的Edge和Chrome都没发现问题，写了个Vue2的案例，你试试在你电脑里看会不会出现同样的问题。  

https://github.com/idrawjs/example/tree/main/packages/vue2

**Comment by SaitamaSiSi** [comment]
@chenshenhai 
谢谢您的Demo，经过排查，我发现是在main.js中引用了 default-passive-events 模块所导致的，移除后就正常了，再次谢谢您的帮助

**Comment by SaitamaSiSi** [comment]
@chenshenhai
你好，我还有问题想请教一下：
1. 如何能够清空画布中的所有历史操作记录，就是清空后就无法撤回或者重做了
2. 怎么加入视频元素到画布中，我看idraw的HTML元素好像不支持依赖资源渲染

**Comment by chenshenhai** [comment]
@SaitamaSiSi 
- 暂时没有实现清空历史操作记录的API
- 目前 `iDraw.js` 不支持画布渲染 视频元素
