### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by EasonMar** [idrawjs/idraw#132]
是否考虑针对 文本元素 增加一个可配置参数 maxWidth。
有些场景下，文本元素 的文本长度是不确定的，需要让文字自适应文本渲染区域，因此有此需求。

Related API: ctx.fillText(text, x, y, [maxWidth]);
maxWidth (可选)：绘制的最大宽度。如果指定了值，并且经过计算字符串的值比最大宽度还要宽，字体为了适应会水平缩放（如果通过水平缩放当前字体，可以进行有效的或者合理可读的处理）或者使用小号的字体 --- from MDN

**Comment by chenshenhai** [comment]
@EasonMar 感谢您的建议，如果用maxWidth的话，会导致文字水平缩放，也就是文字拉伸变形了。
这个之前有考虑过但是设计`iDraw.js` 之初，没打算让文字变形，但是可以讨论看看文字变形功能是否有实际使用意义。

**Comment by EasonMar** [comment]
在一些特殊场景，还是有这个需求的；比如使用canvas制作通知书：使用通知书模板作为底图，通知书有些信息栏，只空出了固定长度的空白区域，但是信息内容长短不一；如果不能让文字自适应这个区域，可能会导致文字超出覆盖掉其他内容，这时候文字稍有变形是可以接受的。如果涉及一个可选的maxWitdh（不配置还是保持以前的特性），就可以解决这个场景需求。

**Comment by chenshenhai** [comment]
@EasonMar  暂时不考虑弹性显示文本元素，因为`iDraw.js`是基于Canvas绘制，涉及大量像素逻辑计算，所有内容需要统一受限于`w`和`h`属性。
