### ISSUE TITLE
Idraw画布监听

### ISSUE THREAD

**Issue by SaitamaSiSi** [idrawjs/idraw#135]
请问一下Idraw中的Canvas的画布监听可以监听鼠标的位置吗？或者说自己添加新的监听事件，比如鼠标滑过或者鼠标单击，按下之类的

**Comment by chenshenhai** [comment]
@SaitamaSiSi 您好，暂时没有相关事件提供，

目前只有监听 Canvas里元素的操作事件 https://idraw.js.org/docs/zh/api/event.html

**Comment by SaitamaSiSi** [comment]
@chenshenhai
那请问一下Idraw/Studio中的拖动元素放置到画布上是怎么实现的呢，添加元素的时候怎么定位到鼠标的位置的呢？

**Comment by chenshenhai** [comment]
@SaitamaSiSi 具体你可以看参考这部分代码 https://github.com/idrawjs/studio/blob/89acbee2a393ab156afedfb240890f6bcb6f4016/src/mods/selector/index.tsx#L27
