### ISSUE TITLE
浏览器支持

### ISSUE THREAD

**Issue by SaitamaSiSi** [idrawjs/idraw#139]
请问一下，Idraw对 IE10 / IE11 这类浏览器支持吗，因为我在谷歌浏览器能正常运行，但在IE11上提示错误
![image](https://user-images.githubusercontent.com/70926594/164412837-5a8b4e96-68b2-4c7c-922b-886f138a1133.png)

**Comment by chenshenhai** [comment]
@SaitamaSiSi   Canvas的2D绘制IE10-11是支持的  https://caniuse.com/?search=CanvasRenderingContext2D 

你遇到的报错是ES6的Symbol报错，必须要引用 polyfill 解决，你可以尝试加入 babel的polyfill https://babeljs.io/docs/en/babel-polyfill.html 或者 es5-shim https://www.npmjs.com/package/es5-shim

**Comment by SaitamaSiSi** [comment]
谢谢您的回复，我设置了polyfill后，在调用setdata的时候报调用的对象无效
![image](https://user-images.githubusercontent.com/70926594/164587178-8e12dee2-1db8-49e9-a357-8d1154d4c2f1.png)

![image](https://user-images.githubusercontent.com/70926594/164587393-d92f0f68-3973-4b28-90b2-171ad0d70930.png)

![image](https://user-images.githubusercontent.com/70926594/164587420-42a38201-904d-4403-a40f-c14e21660aa8.png)

![image](https://user-images.githubusercontent.com/70926594/164587584-91b6a47f-c255-4797-b4f0-fc406c38f2f1.png)

**Comment by SaitamaSiSi** [comment]
经过测试后，发现用调试模式下运行会报这个错误，但在发布程序之后再运行就正常了，可能是我调试模式的一些设置问题吧，谢谢您的帮助
