### ISSUE TITLE
Question:创建HTML元素

### ISSUE THREAD

**Issue by SaitamaSiSi** [idrawjs/idraw#140]
你好，在创建HTML元素内容时，文本内容中存在 &nbsp 这种空格符号的时候，无法正常加载元素，下面的信息是在谷歌浏览器中，HTML元素Demo中 Button 改为 &nbspButton 出现的

![image](https://user-images.githubusercontent.com/70926594/165685416-3d3b0b8b-30d9-420d-8904-2bc81d700ba6.png)

**Comment by chenshenhai** [comment]
@SaitamaSiSi 您好，请问能否提供复现问题的 HTML 代码片段

**Comment by SaitamaSiSi** [comment]
@chenshenhai 你好，我是直接在Demo演示网站上加入的 &nbsp

![image](https://user-images.githubusercontent.com/70926594/165896100-79a889c8-aab4-41d2-a283-c8df4d6321f5.png)

**Comment by chenshenhai** [comment]
@SaitamaSiSi  已修复，更新到 `0.3.0-alpha.2` 版本

**Comment by SaitamaSiSi** [comment]
@chenshenhai 你好，我又有一个问题想要请教一下，我在往iDraw中添加Html元素后，在谷歌浏览器能够正常显示，但是在IE11中却显示内容为空，元素是成功添加进去了，因为可以进行选中移动操作，但是内容没有显示，F12工具中也没有提示错误或者异常

这是我的IE版本
![image](https://user-images.githubusercontent.com/70926594/169478400-2331ab32-2ed2-45a8-9a4a-69431baacaa7.png)

这是我的添加代码
![image](https://user-images.githubusercontent.com/70926594/169478094-ba6bd275-8140-4867-a112-82f612f5c018.png)

使用的Html对象是Demo演示网站上的对象
![image](https://user-images.githubusercontent.com/70926594/169478317-704c83b2-b704-4d04-9f21-caee29035cc5.png)

**Comment by chenshenhai** [comment]
@SaitamaSiSi 您好，iDraw.js没有计划对IE浏览器做兼容，因为IE浏览器官方已经有计划不再维护，2022年6月15日停止支持。
