### ISSUE TITLE
箭头元素

### ISSUE THREAD

**Issue by xu4wang** [idrawjs/idraw#144]
请问有没有计划支持箭头元素？
我想用idraw来画流程图。

谢谢

**Comment by chenshenhai** [comment]
@xu4wang 您好，暂时不考虑箭头函数，也没有做流程图方向。
因为idraw.js是基于Canvas实现的，不适合实现流程图。一般前端实现流程图比较多用SVG来实现。

**Comment by xu4wang** [comment]
OK 了解 。 我看有一些做流程图的工具是用graphviz实现的（比如plantuml），graphviz底层也是用的canvas。
