### ISSUE TITLE
文字似乎不能取消垂直居中,这给我造成了困扰

### ISSUE THREAD

**Issue by JXDS18FUJT** [idrawjs/idraw#145]
我看了一下源码.是无法取消文字元素的垂直居中,能否添加这个功能呢?

**Comment by chenshenhai** [comment]
@JXDS18FUJT  您好，请问方便提供一下问题的最小还原场景的demo代码吗？

**Comment by chenshenhai** [comment]
@JXDS18FUJT  已经在计划加强Canvas渲染文字样式，如果你目前使用过程有困扰，可以先试用idrawjs的 html 的元素类型来绘制文字样式

**Comment by chenshenhai** [comment]
@JXDS18FUJT 已添加文本元素的垂直控制属性。 https://github.com/idrawjs/idraw/pull/167
