### ISSUE TITLE
operation.disableScale和operation.disableRotate不生效

### ISSUE THREAD

**Issue by ZzZzZzjw** [idrawjs/idraw#149]
我看了在Oct 24, 2021 文件packages/core/src/lib/helper.ts的提交更改 您把disableScale拼写成了disbaleScale ，导致disableScale和disableRotate不生效，以下是您的更改：
 topLeft: {
          x: elem.x - controllerSize - bw,
          y: elem.y - controllerSize - bw,
          invisible: hideObliqueDirection,
          invisible: hideObliqueDirection || elem?.operation?.**disbaleScale** === true,
        },

**Comment by chenshenhai** [comment]
@ZzZzZzjw 您好，问题已经解决，谢谢提醒
