### ISSUE TITLE
为什么拖动后的元素对比未拖动的元素 看起来好像更模糊了

### ISSUE THREAD

**Issue by ZzZzZzjw** [idrawjs/idraw#154]
![image](https://user-images.githubusercontent.com/93759802/212285746-cf9f7412-fb68-43b5-9974-3210833ba170.png)
左边是未进行拖动的圆形元素 右边是拖动后的圆形元素
明显感觉两个元素看起来不一样

**Comment by chenshenhai** [comment]
@ZzZzZzjw 请问能提供复原问题的代码片段或demo吗？

**Comment by ZzZzZzjw** [comment]
我写了一个demo  开始我发现demo里的元素拖动后不会出现我上面说的问题 然后我排查了一下 发现是使用idraw.scale（）对画布进行放大之后 再进行拖动就会出现上面的问题 而且拖动到不同的位置感觉图形还不一样 
![image](https://user-images.githubusercontent.com/93759802/212581985-26a6aa1c-6b62-4fa0-92c7-3dc9069e96c0.png)
![image](https://user-images.githubusercontent.com/93759802/212582000-ff4a2cea-1e3a-472b-be19-4008222d0874.png)
![image](https://user-images.githubusercontent.com/93759802/212582109-c2512fca-576f-4abc-aa4d-5202d7c1b202.png)

[vue-idraw.zip](https://github.com/idrawjs/idraw/files/10421926/vue-idraw.zip)

**Comment by chenshenhai** [comment]
@ZzZzZzjw 感谢提供问题demo，我后续周末空闲排查一下问题

**Comment by chenshenhai** [comment]
@ZzZzZzjw  您好，经过检查，这个是因为Canvas绘制位图，不是矢量图，所以放大是会模糊的。这个是Canvas本身绘制能力限制的，idrawjs的放大功能，就是将位图直接放大。

**Comment by chenshenhai** [comment]
计划在1.0版本进行视图放大的“像素化”处理，如下图所示：
![image](https://user-images.githubusercontent.com/8216630/226387121-aaf07538-fbfe-4bad-acc1-6af685cb3498.png)

**Comment by chenshenhai** [comment]
@ZzZzZzjw  0.4版本 开始，已经实现矢量图形显示，除了图片元素外，其它图形的放大不会变模糊了。
