### ISSUE TITLE
清除选中状态

### ISSUE THREAD

**Issue by SaitamaSiSi** [idrawjs/idraw#155]
有一个小小的建议，既然有选中元素的方法，那么建议可以加上取消元素选中的方法。

**Comment by chenshenhai** [comment]
这个建议好，可以考虑用   `idraw.cancel('uuid')` 的方式来取消选中元素

**Comment by chenshenhai** [comment]
Implemented: https://github.com/idrawjs/idraw/pull/164  in the version `0.3.0-alpha.8`

已实现
