### ISSUE TITLE
1是否可以增加 旋转功能锁定的配置 2点击元素不移动元素也会触发changeData事件

### ISSUE THREAD

**Issue by yddydd007** [idrawjs/idraw#159]
1是否可以增加 旋转功能锁定的配置  true or false 来控制 元素是否可以被旋转
2只是点击元素并不移动元素也会触发changeData事件

**Comment by chenshenhai** [comment]
@yddydd007  您好！
关于问题1，idraw.js 就已经支持了对单独元素禁用旋转的个功能，属性为 `operation.disableRotate `，具体可以查看文档 https://idraw.js.org/docs/zh/element/info.html#%E7%94%BB%E5%9B%BE%E5%85%83%E7%B4%A0%E7%9A%84%E4%BF%A1%E6%81%AF 

关于问题2，待我花点时间排查一下。

**Comment by chenshenhai** [comment]
@yddydd007  问题1 已解决，请更新到 0.3.0-alpha.7 版本
