### ISSUE TITLE
Studio里面的双击文本编辑功能，API在什么地方？谢谢

### ISSUE THREAD

**Issue by chenzhenyun** [idrawjs/idraw#180]

**Comment by chenshenhai** [comment]
@chenzhenyun  您好， `idraw`目前没有双击文本编辑的功能。
`@idraw/studio` 之所以能进行双击编辑文字，是因为`idraw`提供对元素的监听双击事件，然后`@idraw/studio`内部动态渲染一个 `textarea`来处理文字的编辑。
