### ISSUE TITLE
你好，我想问下，文本如果给的字号过大，比如200，我应该怎么给高度呢

### ISSUE THREAD

**Issue by hqhhtzj** [idrawjs/idraw#198]
文字的字号是动态的，如果字号过大，给的高度h过小，字直接显示不了了。就是怎么动态求出字体的高度，idraw有咩有相应的api啊，相应的更新元素。文字的高度不是自适应的吗？

**Comment by chenshenhai** [comment]
> 文字的字号是动态的，如果字号过大，给的高度h过小，字直接显示不了了。就是怎么动态求出字体的高度，idraw有咩有相应的api啊，相应的更新元素。文字的高度不是自适应的吗？

idraw.js里的元素大小是通过高度属性`h`控制的，当`text`文案换变化，是不会自动去修改`h`属性，也就是文字高度不会受到文字内容做自适应的，要不然就会出现和控制`h`的冲突
