### ISSUE TITLE
大量Node和edge下重新绘制卡顿。

### ISSUE THREAD

**Issue by 258796535** [idrawjs/idraw#203]
大量Node和edge下重新绘制卡顿，如何实习局部重新绘制，而不是整个页面都重新绘制，这样导致性能下降厉害。

**Comment by chenshenhai** [comment]
@258796535 您好，麻烦提供一下还原问题的最小demo，谢谢！

**Comment by chenshenhai** [comment]
超过两周没提供相关信息，关闭该issue
