### ISSUE TITLE
onlyRender true or false does not make a difference

### ISSUE THREAD

**Issue by evandor** [idrawjs/idraw#229]
Maybe my expectations are misled: I understood that "onlyRender" kind-of should prevent any changes to the drawing (something like a "read-only mode"), but when I change it to true (for example in https://idraw.js.org/playground/?demo=options), I cannot see any change in behaviour. 

If it is not related to a read-only mode, maybe this mode could be a nice new feature? 

My use-case would be that I can define a fancy drawing (in the normal, drawing mode), for example a mind-map, and then, in a different mode, me or another user cannot change the mind-map, but click on its elements to open a new link (instead of changing the mind-map)

**Comment by chenshenhai** [comment]
@evandor Thanks for your feedback, it maybe a bug.

At present, i am refactering the whole framework of idraw, I will fix this bug in next version (v0.4.0)

**Comment by chenshenhai** [comment]
I have released the v0.4.0-beta.2 . It can implement `readOnly` feature by `disable*` other operation features.
I provide the demo for you to display the code. https://idraw.js.org/playground/?demo=basic-options
