### ISSUE TITLE
文档里面显示不全

### ISSUE THREAD

**Issue by hqhhtzj** [idrawjs/idraw#257]
文档是裁剪了一些吗？我记得之前看的时候都有screenSelectElement，screenChangeElement，screenMoveElementEnd事件说明。triggerChangeEvent这些参数说明，现在怎么没看到了呢，作者可以把这些参数说明放出来吗，感谢。

**Comment by chenshenhai** [comment]
@hqhhtzj 您好，感谢对iDraw.js的关注。目前v0.4版本是全新重构，还处于beta版本只开放稳定的API，其他未开放的API会在`@idraw/studio`中验证过后，稳定了就会逐步开放。至于现在没开放的API，意味着还不稳定。

您提到的这几个API将在v0.4中废弃，会用其他方式来替代。一旦API稳定了，会更新到文档里的。
