### ISSUE TITLE
operations.lock 新版本不支持了？

### ISSUE THREAD

**Issue by BigGrassDog** [idrawjs/idraw#262]
大佬您好～刚升级了0.4.0-beta.6 版本，发现 operations.lock 不支持锁住元素了？

**Comment by chenshenhai** [comment]
@BigGrassDog  您好，会支持的，还在补全功能，感谢您的反馈。

**Comment by BigGrassDog** [comment]
感谢大佬回复，生产中在用，持续关注更新。微信来，请你喝咖啡～

**Comment by BigGrassDog** [comment]
> @BigGrassDog 您好，会支持的，目前已补全功能，感谢您的反馈。

感谢大佬回复，生产中在用，持续关注更新。微信来，请你喝咖啡～

**Comment by chenshenhai** [comment]
@BigGrassDog 已补全lock功能 https://github.com/idrawjs/idraw/pull/271， `0.4.0-beta.10` 版本已经生效。
