### ISSUE TITLE
建议提供 居中 的 API

### ISSUE THREAD

**Issue by leonhu0710** [idrawjs/idraw#268]
类似 antv x6 中的  graph.centerContent() // 将画布中元素居中展示
 https://x6.antv.antgroup.com/tutorial/basic/graph#%E5%B8%B8%E7%94%A8-api

**Comment by chenshenhai** [comment]
@leonhu0710 感谢建议，可以考虑添加该功能

**Comment by chenshenhai** [comment]
已提供 API `idraw.centerContent()`  https://github.com/idrawjs/idraw/pull/271/files#diff-d7307ee91539c66b7c8bc3ae3171ed95e4e4bac9f76793db69c35730079f5ac5R143
