### ISSUE TITLE
Next TS: Build Error - Cannot find module './lib/html' or its corresponding type declarations.

### ISSUE THREAD

**Issue by ekanshrastogi** [idrawjs/idraw#274]
When running the build command in the next ts application. I am getting following error.

<img width="684" alt="Screenshot 2024-01-31 at 6 19 04 PM" src="https://github.com/idrawjs/idraw/assets/63385555/1bba2ff4-f31a-47d9-8499-e03ffac71391">

using version - "idraw": "0.4.0-beta.10",

**Comment by ekanshrastogi** [comment]
@chenshenhai Thanks for response. 
Can you please let us know when can we expect next version?

**Comment by chenshenhai** [comment]
@chenshenhai I currently maintain iDraw.js and release new version every weekend. Because I can only use my space time to maintain it.

**Comment by chenshenhai** [comment]
@ekanshrastogi I will fix the issue and release next version this weekend.  Because I can only use space time to maintain iDraw.js.

**Comment by chenshenhai** [comment]
@ekanshrastogi  I have fixed this issue in version `0.4.0-beta.11`

**Comment by ekanshrastogi** [comment]
Thanks a lot!
