### ISSUE TITLE
Add rotation handle.

### ISSUE THREAD

**Issue by Peterksharma** [idrawjs/idraw#276]
I am working on attaching a rotation handle to the element but having a few issues. I have taken the approach of adding the handle to the wrapper in the selector. I want the handle to have access to the mouse down, mouse up, and the mouse move and update the angle of the element base off of where the handle is updated.

**Comment by chenshenhai** [comment]
@Peterksharma  Thanks for your suggestion. I already had plans to develop this feature in the future.

**Comment by Peterksharma** [comment]
Do you have a roadmap for when it will be developed? Would I be able to hire you for help?

**Comment by chenshenhai** [comment]
@Peterksharma Hi, I plan to implement this feature about rotation before the end of Feb.

At percent, you don't need to hire me. iDraw.js is my hobby project in my space time, and I currently developing it based on my interest.

**Comment by chenshenhai** [comment]
@Peterksharma Hi, I have implemented rotation handle of element
