### ISSUE TITLE
Problem when importing

### ISSUE THREAD

**Issue by inanlia** [idrawjs/idraw#279]
When i used CDN i get this error:

> Uncaught TypeError: iDraw is not a constructor

When i used the node package i get this error:

> Uncaught TypeError: The token “idraw” was a bare null token but was not mapped to anything. Relative module specifiers must begin with “./”, “../” or “/”.

This just might be an error on my part but any help would be very much appreciated.

**Comment by chenshenhai** [comment]
This is a typo in the document usage and has been corrected.  The correct usage is like this: 

```html
<script src="https://unpkg.com/idraw"></script>
<script>
  (function () {
    const { iDraw } = window.iDraw;
    const app = document.querySelector('#app');
    const idraw = new iDraw(app, {
      width: 600,
      height: 400,
      devicePixelRatio: 2
    });
  })();
</script>

```
