### ISSUE TITLE
[Feature Request] Is it possible to snap element to grid?

### ISSUE THREAD

**Issue by FFengIll** [idrawjs/idraw#288]
`Snap to grid` is a feature in many view editors, and is common in PPT.
Will idraw support it? (or I missed it?)

**Comment by FFengIll** [comment]
> `Snap to grid` is a feature in many view editors, and is common in PPT. Will idraw support it?

@chenshenhai sorry for the poor description before. Pls see the updated.

Thx for the respond.

**Comment by chenshenhai** [comment]
@FFengIll Thanks your feedbacks. Currently, iDraw.js uses custom pixels to define size and position, and does not consider grid specifications for the time being.
