### ISSUE TITLE
idraw是否有微信群或社群？

### ISSUE THREAD

**Issue by xeoshow** [idrawjs/idraw#292]
如题，谢谢

**Comment by chenshenhai** [comment]
@xeoshow 您好，感谢对`iDraw.js`的关注，目前暂不考虑微信群，因为微信群不适合做技术讨论，有任何问题或者建议，可以在GitHub提issue，或者在 https://github.com/idrawjs/idraw/discussions 这里发帖讨论。

**Comment by xeoshow** [comment]
谢谢。

**Comment by xeoshow** [comment]
在这里加了一个讨论：
https://github.com/idrawjs/idraw/discussions/295
