### ISSUE TITLE
文本对象显示问题

### ISSUE THREAD

**Issue by SaitamaSiSi** [idrawjs/idraw#303]
你好，我想请教一下Idraw关于文本对象设置的问题。
![image](https://github.com/idrawjs/idraw/assets/70926594/8880b3a0-0807-4a79-acab-0db0ea18284c)
当我如上图所示，borderWidth为0，文本框宽度为200，字号为99.9，可以完整显示两个文字内容。
![image](https://github.com/idrawjs/idraw/assets/70926594/be32e189-3ffc-4bdf-bf5b-ec8f1a85c7ff)
但是当我将字号设置为100时，两个文字长度应该正好等于宽度，应该显示两个文字，但是却只显示了一个文字，是有什么内容占了1像素宽度吗？有办法可以去除吗？

**Comment by SaitamaSiSi** [comment]
![image](https://github.com/idrawjs/idraw/assets/70926594/8553a1a5-73f5-4684-89da-2032fe39dc68)
通过观察renderer/src/draw/text.ts文件中的drawText方法发现，当文字宽度正好等于框宽度时，会进入else语句中当作新的一行，是否可以在中间加入判断等于框宽度的情况，目前本地修改后测试可行。

**Comment by SaitamaSiSi** [comment]
![image](https://github.com/idrawjs/idraw/assets/70926594/faa358cb-b400-41e1-968f-2a55bd399680)
你好，我通过观察renderer/src/draw/text.ts文件中的drawText方法发现，当文字宽度正好等于框宽度时，会进入else语句中当作新的一行，是否可以在中间加入判断等于框宽度的情况，目前本地修改后测试可行。

**Comment by chenshenhai** [comment]
@SaitamaSiSi 您好，感谢指出问题，本周末会修复和发布最新版本。

**Comment by chenshenhai** [comment]
@SaitamaSiSi 已修复，请使用最新版本 `v0.4.0-beta.19`

**Comment by SaitamaSiSi** [comment]
你好，请问能否在0.3.0-alpha.6版本中也增加此更新呢，因为发现0.3.0版本和0.4.0版本区别较大
