### ISSUE TITLE
@idraw/studio中

### ISSUE THREAD

**Issue by hqhhtzj** [idrawjs/idraw#310]
作者，你好，之前我们用0.3的版本，有下面这些，但是现在0.4的版本没有下面这些了
screenSelectElement，screenChangeElement，screenMoveElementEnd，selectElementByIndex这些好像都报错了
这些Api什么时候可以更新到文档中啊，我找文档中没看到呢
我看到@idraw/studio里面有好多功能恰好是我们需要的。有没有详细的文档说明啊

**Comment by hqhhtzj** [comment]
还有redo和undo这两个api也不行了

**Comment by chenshenhai** [comment]
@hqhhtzj 您好，感谢对iDraw.js的关注，目前iDraw.js和@idraw/studio 的0.4版本还处于beta和alpha阶段，很多功能处于规划和开发阶段，暂时没有相关文档。
