### ISSUE TITLE
官网首页 demo bug

### ISSUE THREAD

**Issue by daiwa233** [idrawjs/idraw#59]
鼠标在长按时移出 canvas 外，再移入 canvas，此时鼠标在 canvas 中移动会导致图形缩放

**Comment by chenshenhai** [comment]
@daiwa233 谢谢指正，需要加个鼠标离开事件后解除画板控制。

**Comment by chenshenhai** [comment]
@daiwa233 已经修复iframe嵌套，事件监听问题  https://github.com/idrawjs/idraw/pull/108
