### ISSUE TITLE
[功能建议] 编辑器面板键盘控制能力（删除、移动、撤销等等）

### ISSUE THREAD

**Issue by mycoin** [idrawjs/idraw#74]
为扩展输入便捷性，希望通过键盘控制主面板。

触发时机：focus到面板即开始监听。

- Command+Z 实现撤销本次操作
- Delete 实现删除选中的层，然后自动聚焦到下一层
- 光标没有focus到输入型控件，上下移动位置/如果同时按住Shift更快的移动。
- 拖拽层的时候，如果按下shift键盘，可以实现固定方向移动 

😄

**Comment by chenshenhai** [comment]
I have implemented the keyborad-events these are copy, cut, delete and paste for controlling elements

https://github.com/idrawjs/idraw/pull/75

**Comment by chenshenhai** [comment]
@mycoin 最新版本已支持快捷键 元素的粘贴，复制，切切 和 操作的撤销
