### ISSUE TITLE
旋转后，拖拉大小出现问题

### ISSUE THREAD

**Issue by lecepin** [idrawjs/idraw#93]

**Comment by chenshenhai** [comment]
@lecepin  请问是 Playground的案例，还是Studio的案例

**Comment by chenshenhai** [comment]
@lecepin 我知道原因了，多谢指正，后续会迭代改正

**Comment by chenshenhai** [comment]
@lecepin 其实 底层idraw已经修复了，Playground的案例依赖的版本已经改正过了，Studio依赖的版本还没更新哈

**Comment by chenshenhai** [comment]
已经修复 https://github.com/idrawjs/idraw/pull/94 ，暂时在旋转时候保留4个方向的缩放计算，剩下4个后续迭代再添加
