### ISSUE TITLE
如何导出合成的结果呢?

### ISSUE THREAD

**Issue by roseforyou** [idrawjs/idraw#97]
1. 在API中, 没有看到相应的介绍, 能想到的是 canvas的 toDataURL 方法, 
但如果有托拽框的, 也会导出, 如保在导出前先取消选中?

2. bug? 选中后, 得点击画布上两次才能取消选中状态

**Comment by chenshenhai** [comment]
@roseforyou 感谢您对 iDraw.js的支持。关于您提到的问题点如下
- 1. 在API里有两中导出结果方式
    - `getData()` 获取图画的JSON数据，后续可作为编辑数据通过 `setData()`导入画布中。
    - `exportDataURL('image/png')` 可以直接导出图画的 base64 数据，可以直接用来渲染图片。这个API还未及时更新到文档，你可以先使用这个API
- 2. 选中元素后，要在空白区域点击两次才取消选择，这个的确是BUG，我后续更新到  TODO List 的issue中。

**Comment by chenshenhai** [comment]
已修复选中元素后，要在空白区域点击两次才取消选择 https://github.com/idrawjs/idraw/pull/99

**Comment by chenshenhai** [comment]
`exportDataURL()` 已经更新到文档中。  https://idraw.js.org/docs/zh/api/export-data-url.html
